### ISSUE TITLE
issue#21 Imagenes ejercicios para la api

### ISSUE THREAD

**Issue by AlvaroGalle** [deiivvv/GymTracker#21]
Enlace imágenes -> https://eresfitness.com/ejercicios/  
430x430 png

Guardar todas las imágenes en formato png sin fondo. En la ubicación resources/static/images/ejercicios/
Todas las imágenes deben tener el mismo tamaño 430x430, en los casos aislados de fuerza mayor que no se pueda, el tamaño deberá se mayor al indicado, nunca menor. Y siempre en forma cuadrada.
y el nombre debe coincidir con el nombre que tienen los inserts de la apis.
Si quiere añadir ejercicios nuevos, ponerlos AL FINAL de los inserts de la api.
En la medida de lo posible todas las imágenes de los ejercicios seguirán el mismo formato y/o estilo.
--------IMPORTANTE--------
Si no se encuentra algún ejercicio, puede ser modificado su nombre, descripción... pero NUNCA borrar el insert, ni cambiar el orden, para no generar problemas con los ids.
--------IMPORTANTE--------

**Comment by deiivvv** [comment]
ready papi
